[package]
name = "pocker"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
itertools = "0.13.0"
clap = "4.5.9"
message-io = { version = "0.18", default-features = false, features = ["tcp"] }
bincode = "1.3.3"
serde = { version = "1.0.204", features = ["derive"] }
